name: Close Issues on PR Merge to Dev

on:
  pull_request:
    types:
      - closed

jobs:
  close-issues:
    if: github.event.pull_request.merged == true && github.event.pull_request.base.ref == 'dev'
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Close related issues
        run: |
          issues=$(echo "${{ github.event.pull_request.body }}" | grep -oP '(?<=#)\d+')
          echo "Issues to close: $issues"
          for issue in $issues; do
            curl -X PATCH -H "Authorization: token ${{ secrets.GITHUB_TOKEN }}" \
                 -H "Accept: application/vnd.github.v3+json" \
                 https://api.github.com/repos/${{ github.repository }}/issues/$issue \
                 -d '{"state": "closed"}'
          done
